openapi: 3.0.0
info:
  version: 1.0.0
  title: Human Resource Development Application
servers:
  - url: https://localhost:3000
    description: 'Development server'

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Bearer with JWT Token'

paths:
  /v1/user/changePassword/{userId}:
    patch:
      summary: Change password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '200':
          description: Success
  /v1/user/viewProfile/{userId}:
    get:
      summary: View profile
      responses:
        '200':
          description: Success
  /v1/admin/register:
    post:
      summary: Add employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                jobPosition:
                  type: string
                department:
                  type: string
                salary:
                  type: number
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Success
  /v1/admin/getAllUsers:
    get:
      summary: Get all employee data
      responses:
        '200':
          description: Success
  /v1/admin/getUser/{userId}:
    get:
      summary: Get data by id
      responses:
        '200':
          description: Success
  /v1/admin/update/{userId}:
    put:
      summary: Update job / salary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                salary:
                  type: number
                jobPosition:
                  type: string
      responses:
        '200':
          description: Success
  /v1/admin/delete/{userId}:
    delete:
      summary: Delete user
      responses:
        '200':
          description: Success
  /:
    get:
      summary: Home
      responses:
        '200':
          description: Success
  /v1/auth/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
